name: Daily Telegram Bot

on:
  schedule:
    - cron: "0 0 * * *" # 07:00 Việt Nam
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Send Telegram message
        run: npm run send
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          LOCATION_NAME: ${{ secrets.LOCATION_NAME }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          SEND_ON_START: "true"