name: Full Info Morning

on:
  schedule:
    - cron: "30 23 * * *" # 06:30 Việt Nam
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run send
        env:
          MESSAGE_TYPE: full
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          LOCATION_NAME: ${{ secrets.LOCATION_NAME }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          SEND_ON_START: "true"